kwpastebin/urls.py
from django.urls import re_path
from kwpastebin import views

app_name = "kwpastebin"

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^mine/$', views.my_pastes, name='my_pastes'),
    re_path(r'^all/$', views.all_pastes, name='all_pastes'),
    re_path(r'^invalidate_cache/$', views.invalidate_cache, name='invalidate_cache'),
    re_path(r'^(?P<id>.*?)/edit/$', views.edit_paste, name='edit_paste'),
    re_path(r'^(?P<id>.*?)/delete/$', views.delete_paste, name='delete_paste'),
    re_path(r'^(?P<id>.*?)/invalidate_cache/$', views.invalidate_cache_for_paste, name='invalidate_cache_for_paste'),
    re_path(r'^(?P<id>.*?)/raw/$', views.show_paste_raw, name='show_paste_raw'),
    re_path(r'^(?P<id>.*?)/$', views.show_paste, name='show_paste'),
]

kwpastebin/templates/kwpastebin/all_pastes.html
{% extends 'base.html' %}
{% load kwpastebin_extras %}
{% block content %}
{% if pastes %}
<ul>
    {% for paste in pastes %}
        {% paste_li paste %}
    {% endfor %}
</ul>
{% else %}
No pastes found.
{% endif %}

{% if perms.kwpastebin.invalidate_cache %}
<form action="{% url 'kwpastebin:invalidate_cache' %}" method="POST">{% csrf_token %}<button class="btn btn-danger btn-sm">Invalidate cache for all pastes</button></form>
{% endif %}
{% endblock content %}

kwpastebin/templates/kwpastebin/delete_paste.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="POST" style="text-align: center;">{% csrf_token %}<button type="submit" name="act" value="confirm" class="btn btn-lg btn-danger">Confirm</button> <button type="submit" name="act" value="cancel" class="btn btn-lg btn-default">Cancel</button></form>
{% endblock %}

kwpastebin/templates/kwpastebin/edit_paste.html
{% extends 'base.html' %}
{% load kwpastebin_extras %}
{% block content %}
{% paste_form form paste %}
{% endblock content %}

kwpastebin/templates/kwpastebin/index.html
{% extends 'base.html' %}
{% load kwpastebin_extras %}
{% block content %}
{% if user.is_authenticated %}
<p><a href="{% url 'kwpastebin:my_pastes' %}">View my pastes</a>{% if perms.kwpastebin.list_all_pastes %} — <a href="{% url 'kwpastebin:all_pastes' %}">View all pastes</a>{% endif %}</p>
{% endif %}
<h2>Public pastes</h2>
{% if public_pastes %}
<ul>
{% for paste in public_pastes %}
    {% paste_li paste %}
{% endfor %}
</ul>
{% else %}
<p class="text-warning">There are no public pastes.</p>
{% endif %}
<h2>Add new paste</h2>
{% if has_add_perm %}
{% paste_form form 0 %}
{% elif user.is_authenticated %}
<p class="text-warning">You do not have permission to create new pastes.</p>
{% else %}
<p class="text-warning">Only logged-in users can add pastes.</p>
{% endif %}
{% endblock content %}

kwpastebin/templates/kwpastebin/my_pastes.html
{% extends 'base.html' %}
{% load kwpastebin_extras %}
{% block content %}
{% if pastes %}
<ul>
    {% for paste in pastes %}
        {% paste_li paste %}
    {% endfor %}
</ul>
{% else %}
No pastes found.
{% endif %}
{% endblock content %}

kwpastebin/templates/kwpastebin/paste.html
{% extends 'base.html' %}
{% load static %}
{% block extra_head %}
<link rel="Stylesheet" href="{% static "paste.css" %}">
{% endblock %}
{% block content %}
<p>created by {{ paste.user_disp }} on {{ paste.date_created|date:"SHORT_DATETIME_FORMAT" }}{% if paste.date_modified != paste.date_created %}, modified {{ paste.date_modified|date:"SHORT_DATETIME_FORMAT" }}{% endif %} —
    <a class="btn btn-primary" href="{% url 'kwpastebin:show_paste_raw' paste.id %}">Raw</a>
    {% if can_change %}<a class="btn btn-info" href="{% url 'kwpastebin:edit_paste' paste.id %}">Edit</a>{% endif %}
    {% if can_delete %}<a class="btn btn-danger" href="{% url 'kwpastebin:delete_paste' paste.id %}">Delete</a>{% endif %}
    {% if perms.kwpastebin.invalidate_cache %}<a class="btn btn-default btn-sm" href="{% url 'kwpastebin:invalidate_cache_for_paste' paste.id %}">Invalidate cache</a>{% endif %}
</p>
{{ paste.html_or_generate | safe }}
{% endblock %}

kwpastebin/templates/kwpastebin/paste_form.html
<form action="" method="POST">{% csrf_token %}
    {{ form.non_field_errors }}

    {{ form.title }}
    {{ form.title.errors }}
    {{ form.content }}
    {{ form.content.errors }}

    {{ form.language.label_tag }} {{ form.language }}
    {{ form.language.errors }}
    <label for="{{ form.public.id_for_label }}">{{ form.public }} {{ form.public.label }}</label>
    {{ form.public.errors }}
    <button type="submit" class="btn btn-primary">{{ submit_text }}</button>
</form>